### ISSUE TITLE
Push new website over the line

### ISSUE THREAD

**Issue by jducoeur** [typelevel/governance#44]
(Based on a conversation with @rossabaker in Slack -- please correct if there are any errors.)

A while ago (looks like about 7 months as of this writing?), 47 Degrees agreed to help Typelevel refresh the website into a newer, snazzier form.  They built a pretty slick prototype -- [the repo can be found here](https://github.com/47degrees/typelevel.github.com), and [the running site can be found here](https://47degrees.github.io/typelevel.github.com/).

Unfortunately, that project wasn't completed, and there has been membership turnover since then, so it isn't at all clear what the current state of things is.  Ross has opened [a PR to update lots of the details](https://github.com/47degrees/typelevel.github.com/pull/21), but that hasn't been merged yet, and we don't know whether 47 Degrees is interested in continuing the project.

So there are several tasks needed here:

* Talk to 47 Degrees, and see if they are still interested in helping out.
* Check out Ross' PR, refresh further if needed, and get it merged.
* Review the new site to make sure there are no obvious regressions against the current live site.
* Replace the live site with this.

**Comment by rossabaker** [comment]
I have updated the PR.  Two things that still seem missing:

1. Most blogs have the placeholder JPEG, and I'm completely overwhelmed finding an appropriate image for 7 years' worth of posts.  Maybe that placeholder is fine.
2. The project list needs to be cleaned up.  See #54 and #55.

**Comment by rossabaker** [comment]
We have a decision to make: do we want the site to be perfect to make a splash, or do we want it to be better than what we have and continue to refine it?  I prefer the latter, but I suck at marketing.

If we go the latter, we're very close, and we need more eyes on it now.

**Comment by jducoeur** [comment]
"Better" is fine, IMO.  While there's something to be said for big-bang marketing, we don't have the resources for it, so taking a more Agile approach of incremental improvement is almost certainly the right way to go.

Hence, I'd say that let's get the new site live, and then we can start making lots of small PRs to make it better.  We don't want any severe regressions, but there's no reason to gold-plate it.

**Comment by rossabaker** [comment]
I have pushed to a [reboot branch](https://github.com/typelevel/typelevel.github.com/tree/reboot) in the original repo.  I'll invite Raul and Israel, but it's mostly technical to get it over the line, so it probably makes sense to finish up in the original repo.

**Comment by rossabaker** [comment]
Follow along [here](https://github.com/typelevel/typelevel.github.com/labels/reboot).

**Comment by rossabaker** [comment]
This isn't automatically synchronized from the reboot branch of the Typelevel repo, but for those who can't run `bundler` or `nix`:

1. https://rossabaker.github.io/typelevel.github.com/ (temporary, will be deleted when this project launches)
2. When you're done reviewing, go install Nix!

**Comment by JasnaMRB** [comment]
Addressed https://github.com/typelevel/typelevel.github.com/pull/388 Thank you all for the support! I'll draft up an announcement blog post soon if others don't beat me to it.

**Comment by alexandru** [comment]
Hi all,

This is a fairly late feedback, sorry for it.

I noticed the new design due to my feed reader complaining that the RSS feed is gone. Please bring [typelevel.org/blog/feed.rss](https://typelevel.org/blog/feed.rss) back 🥺🙏

And, I know you worked hard on the new redesign, and a refresh was overdue. But, on first seeing it, I got these feelings:

1. the look and feel is corporate — maybe it's due to the desaturation, maybe it's due to the black and white picture of the guy staring at the screen; colors are cool, and the new look is colorless and lacks contrast;
2. those animations are nauseating (sorry for my visceral reaction); impatient people that simply scroll down, will mostly see a blank page, due to the animations being slow; also, given I noticed annoying lag while scrolling, I opened Chrome's Task Manager, and the GPU seems to take a hit, reminding me of Flash-powered websites (this on an Intel MacBook Pro from 2021);
3. the blog is designed for articles with images, in newspaper/magazine format (multiple rows), but there are no images, the titles are not clickbait, publishing frequency is low, and Typelevel's blog isn't a newspaper;

I know you're contributing in your free time, and this redesign took effort. Just take this feedback under consideration, the next time someone is in the mood for tweaking some CSS 🙂

But please bring back the RSS/Atom feed 🙏

You're awesome!

Thanks,

**Comment by jducoeur** [comment]
Thanks for the feedback!  At the least, the loss of the RSS feed is clearly a regression that we need to look into...
